# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QrGbcPf0NJBbbdjaFVsW_yOR3BPMXJwD
"""

import sys
import numpy as np

def Fibo_Adam(n):
    a, b = 0, 1
    L = []
    while a < n:
        L.append(a)
        a, b = b, a + b
    return L

if __name__ == "__main__":
    try:
        n = int(sys.argv[1])
        L = Fibo_Adam(n)
        print("Fibonacci numbers up to", n, ":", L)
    except (IndexError, ValueError):
        print("Usage: python fibonacci.py <number>")